name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
  - jupyter
  - scikit-learn
  - tensorflow
  - keras

  - pip:
    - nbgitpuller
    - sphinx-gallery
    - gym
